services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_DB=test_db
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - ./postgres-data-test:/var/lib/postgresql/data